export const LOAD_RECIPES_SUCCESS = 'CREATE_RECIPE';
export const LOAD_AUTHORS_SUCCESS  = 'LOAD_RECIPES_SUCCESS';
export const CREATE_RECIPE_SUCCESS  = 'CREATE_RECIPE_SUCCESS';
export const UPDATE_RECIPE_SUCCESS  = 'UPDATE_RECIPE_SUCCESS';
